version: '3.2'
services:
  jenkins_master:
    build: jenkins_master
    ports:
      - '8080:8080'
      - '5000:5000'
      - '50000:50000'
    networks:
      - rito_project_jenkins-net
    volumes:
      - type: volume
        source: jenkins-log
        target: /var/log/jenkins
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
  node_exporter:
    build: ./node_exporter
    ports:
      - '9100:9100'
    volumes:  
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - rito_project_jenkins-net
    
  cadvisor:
    build: ./cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8069:8080'
    networks:
      - rito_project_jenkins-net    

  prometheus:
    build: ./prometheus
    volumes:
      - prometheus_data:/prometheus
    dns:
      - "8.8.8.8"
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml  
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    
    depends_on: 
      - cadvisor
    networks:
      - rito_project_jenkins-net    
  
  
  grafana:
    build: ./grafana
    ports:
    - '3000:3000'
    depends_on: 
    - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/files/:/etc/grafana/provisioning/
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=BABACECA
      - GF_USERS_ALLOW_SIGN_UP=false

    networks:
    - rito_project_jenkins-net      

volumes:
  jenkins-log:
  jenkins-data:
  prometheus_data:
  grafana_data:
networks:
  rito_project_jenkins-net:
