version: "3.2"
services:
  jenkins_master:
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "5000:5000"
    
    volumes:
      - type: volume 
        source: jenkins-log
        target: "/var/log/jenkins"
      - type: volume
        source: jenkins-data
        target: "/var/jenkins_home"
          
volumes: 
  jenkins-log:
  jenkins-data:
  