version: '3.2'
services:
  jenkins_master:
    build: jenkins_master
    expose:
      - '8080'
    ports:
      - '8080:8080'
      - '5000:5000'
    networks:
      - rito_project_jenkins-net
    volumes:
      - type: volume
        source: jenkins-log
        target: /var/log/jenkins
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
  nginx_proxy:
    build: ./jenkins_nginx
    expose:
      - '80'
    ports:
      - '8070:80'
    networks:
      - rito_project_jenkins-net
  jenkins-slave:
    build: ./jenkins_slave
    networks:
      - rito_project_jenkins-net

  cadvisor:
    build: ./cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8069:8080'
    networks:
      - rito_project_jenkins-net    

  prometheus:
    build: ./prometheus
    volumes:
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml  
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    
    depends_on: 
      - cadvisor
    networks:
      - rito_project_jenkins-net    
  
  
  grafana:
    build: ./grafana
    ports:
    - '3000:3000'
    networks:
    - rito_project_jenkins-net      

volumes:
  jenkins-log:
  jenkins-data:
  prometheus_data:
networks:
  rito_project_jenkins-net:
