--- 
    jenkins: 
      agentProtocols: 
        - JNLP4-connect
        - Ping
      clouds: 
        - 
          docker: 
            dockerApi: 
              connectTimeout: 60
              dockerHost: 
                uri: "tcp://docker.for.win.localhost:2375"
              readTimeout: 60
            name: LocalDockerHost
            templates: 
              - 
                connector: attach
                dockerTemplateBase: 
                  image: rito_project_jenkins-slave
                labelString: testslave
                mode: EXCLUSIVE
                name: testslave
                pullStrategy: PULL_NEVER
                pullTimeout: 300
                remoteFs: /home/jenkins
      crumbIssuer: 
        standard: 
          excludeClientIPFromCrumb: false
      disableRememberMe: false
      labelAtoms: 
        - 
          name: master
        - 
          name: testslave
      markupFormatter: plainText
      mode: NORMAL
      myViewsTabBar: standard
      numExecutors: 2
      primaryView: 
        all: 
          name: all
      projectNamingStrategy: standard
      quietPeriod: 5
      remotingSecurity: 
        enabled: false
      scmCheckoutRetryCount: 0
      slaveAgentPort: 50000
      updateCenter: 
        sites: 
          - 
            id: default
            url: "https://updates.jenkins.io/update-center.json"
      views: 
        - 
          all: 
            name: all
      viewsTabBar: standard
    security: 
      apiToken: 
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      sSHD: 
        port: -1
    unclassified: 
      buildDiscarders: 
        configuredBuildDiscarders: 
          - jobBuildDiscarder
      location: 
        adminAddress: "pavlin.hristov101@gmail.com"
      pollSCM: 
        pollingThreadCount: 10
    