## Install Docker ############################################################

---
- hosts: 127.0.0.1
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-apt', 'unzip']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest   
     
    - name : Update and install git
      apt: update_cache=yes name=git-core state=latest
      
    - name: Recursively change ownership of Jenkins master files
      file:
        path: /usr/src/DevOps/Docker/Rito_Project/jenkins_master/files/
        state: directory
        recurse: yes
        owner: ubuntu
        mode: '0007'

## Instal AWS CLI ########################################################
    - name: Create aws directory
      file:
        path: /usr/bin/awscli
        state: directory
        mode: '0007'

    - name: Download aws cli
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /usr/bin/awscliv2.zip
        mode: '0007'

    - name: Extract aws cli into /usr/bin/aws
      unarchive:
        src: /usr/bin/awscliv2.zip
        dest: /usr/bin/awscli

    - name: install aws cli
      command: /usr/bin/awscli/aws/install

