## Install Docker ############################################################

---
- hosts: 127.0.0.1
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-apt']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest   
    
    - name: return motd to registered var
      command: curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \n apt install docker-compose
  

    - name : Update and install git
      apt: update_cache=yes name=git-core state=latest

    - name: Change docker compose ownership and permissions
      file:
        path: /usr/local/bin/docker-compose
        owner: ubuntu
        mode: '0007'
    
            
    - name: Recursively change ownership of Jenkins master files
      file:
        path: /usr/src/DevOps/Docker/Rito_Project/jenkins_master/files/
        state: directory
        recurse: yes
        owner: ubuntu
      