---
    - hosts: loadbalancer
      become: yes
      tasks:
        - service: name=nginx state=stopped

    - hosts: webserver
      become: yes
      tasks:
        - service: name=apache2 state=stopped

    - hosts: database
      become: yes
      tasks:
        - service: name=mysql state=restarted

    - hosts: loadbalancer
      become: yes
      tasks:
        - service: name=nginx state=started

    - hosts: webserver
      become: yes
      tasks: 
        - service: name=apache2 state=started